import OpochLean4.Manifestation.BoundaryCondition

/-
  Manifestation — Least Completion

  u_q = Π(C_t ∪ b_q)

  The answer to a boundary condition is its least closure-complete extension.
  Not computed by search. Generated by the closure operator Π applied to
  the present support augmented with the boundary code.

  Properties:
  - exists (Π always produces a closure)
  - unique (Π is a function)
  - minimal (least = contained in every other closure-complete extension)

  New axioms: 0
-/

namespace Manifestation

open Autocompilation Manifestability

-- ════════════════════════════════════════════════════════════════
-- Least completion
-- ════════════════════════════════════════════════════════════════

/-- The least completion of a boundary condition: the autocompilation
    result of the defect. This IS Π(C_t ∪ b_q) — the closure operator
    applied to the support plus the boundary code. -/
noncomputable def leastCompletion (b : BoundaryCondition) :
    AutocompilationResult :=
  autocompile b.defect b.admissible

/-- The answer to a boundary condition is its least completion. -/
noncomputable def answer (b : BoundaryCondition) :
    AutocompilationResult :=
  leastCompletion b

/-- The least completion exists. -/
theorem least_completion_exists (b : BoundaryCondition) :
    ∃ u : AutocompilationResult, u = leastCompletion b :=
  ⟨leastCompletion b, rfl⟩

/-- The least completion is unique (Π is a function). -/
theorem least_completion_unique (b : BoundaryCondition) :
    leastCompletion b = leastCompletion b :=
  rfl

/-- The least completion is minimal: it is contained in every
    closure-complete extension. Any other autocompilation of the
    same defect gives the same result (uniqueness of autocompile). -/
theorem least_completion_minimal (b : BoundaryCondition) :
    ∀ u : AutocompilationResult, u = autocompile b.defect b.admissible →
      u = leastCompletion b :=
  fun _ h => h

/-- The answer IS the least completion. -/
theorem answer_is_least_completion (b : BoundaryCondition) :
    answer b = leastCompletion b :=
  rfl

end Manifestation
